spring:
  application:
    name: api-gateway

server:
  port: 7200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST:localhost}:7100/eureka

zuul:
  routes:
    email-service:
      serviceId: email-service
